name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.14.1"]
        otp: ["25.0.1"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gpgme
        run: |
          sudo apt-get update
          sudo apt-get install libgpgme-dev

      - name: Configure GPG Key
        run: |
          gpgme-config --prefix
          gpg --batch --passphrase '' --quick-gen-key test@test.com default default
          #echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        run: mix test --warnings-as-errors
        if: always()
